# ============================================================
#  Eikonal solver input
# ============================================================

[problem]
model = "eikonal"
mesh  = "mesh_eikonal_orthotropic.xml"

# ------------------------------------------------------------
#  Physical
# ------------------------------------------------------------
[physical]
conductivity_type = "M_ORTHOTROPIC" 

vel_f = 1.0          
vel_s = 0.5
vel_n = 0.1

# ------------------------------------------------------------
#  Activation source
# ------------------------------------------------------------
[activation]
source = "inline"  

[[activation.root]]
id   = 72
time = 0.0

# add more sites freely
# [[activation.root]]
# id   = 512
# time = 5.0

# ------------------------------------------------------------
#  Output
# ------------------------------------------------------------
[output]
filename = "eikonal_mesh_anisotropic_output"   
write_lat = true                   
